### ISSUE TITLE
运行命令错误

### ISSUE THREAD

**Issue by Qa7060123** [cgkings/fclone_shell_bot#7]
1

**Comment by Qa7060123** [comment]
> 显示错误
/root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:269
        var handle = new Pipe(constants.SOCKET);
                                       ^

TypeError: Cannot read property 'SOCKET' of undefined
    at new PipeSocket (/root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:269:40)
    at new UnixTerminal (/root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:94:25)
    at Object.spawn (/root/fclone_shell_bot/node_modules/node-pty/lib/index.js:28:12)
    at new Command (/root/fclone_shell_bot/lib/command.js:22:18)
    at Bot.<anonymous> (/root/fclone_shell_bot/server.js:192:25)
    at Bot.<anonymous> (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:87:22)
    at HandlerQueue.callHandler (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:63:29)
    at Bot.<anonymous> (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:86:43)
    at HandlerQueue.callHandler (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:63:29)
    at Bot.<anonymous> (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:86:43)

> 
> 环境：
> python:3.6
> ubuntu16.04

**Comment by Qa7060123** [comment]
> 显示错误
> /root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:269
> var handle = new Pipe(constants.SOCKET);
> ^
> 
> TypeError: Cannot read property 'SOCKET' of undefined
> at new PipeSocket (/root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:269:40)
> at new UnixTerminal (/root/fclone_shell_bot/node_modules/node-pty/lib/unixTerminal.js:94:25)
> at Object.spawn (/root/fclone_shell_bot/node_modules/node-pty/lib/index.js:28:12)
> at new Command (/root/fclone_shell_bot/lib/command.js:22:18)
> at Bot. (/root/fclone_shell_bot/server.js:192:25)
> at Bot. (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:87:22)
> at HandlerQueue.callHandler (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:63:29)
> at Bot. (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:86:43)
> at HandlerQueue.callHandler (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:63:29)
> at Bot. (/root/fclone_shell_bot/node_modules/botgram/lib/message.js:86:43)
> 
> 环境：
> python:3.6
> ubuntu16.04

**Comment by cgkings** [comment]
建议按照shellbot手动安装教程，把环境再装一下，应该是安装时有错误，你没注意
